//alert constants
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//loading constant
export const INITIAL_LOADING = "INITIAL_LOADING";
export const LOADING_ON_SUBMIT = "LOADING_ON_SUBMIT";

//errors constnats
export const SET_ERRORS_LIST = "SET_ERRORS_LIST";
export const REMOVE_ERRORS = "REMOVE_ERRORS";

//login, logout, auth constnats
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const AUTH_ERROR = "AUTH_ERROR";

export const USER_LOADED = "USER_LOADED";

//Email Template Constants
export const EMAIL_TEMPLATE_CREATED = "EMAIL_TEMPLATE_CREATED";
export const EMAIL_TEMPLATE_ERROR = "EMAIL_TEMPLATE_ERROR";
export const DELETE_EMAIL_TEMPLATE = "DELETE_EMAIL_TEMPLATE";
export const EMAIL_TEMPLATE_UPDATED = "EMAIL_TEMPLATE_UPDATED";
export const EMAIL_TEMPLATE_LIST_UPDATED = "EMAIL_TEMPLATE_LIST_UPDATED";
export const GET_EMAIL_TEMPLATE_BY_ID = "GET_EMAIL_TEMPLATE_BY_ID";
export const CHANGE_EMAIL_TEMPLATE_STATUS = "CHANGE_EMAIL_TEMPLATE_STATUS";
export const EMAIL_TEMPLATE_SEARCH_PARAMATERS_UPDATE =
  "EMAIL_TEMPLATE_SEARCH_PARAMATERS_UPDATE";

//Inquiry Constants
export const INQUIRY_CREATED = "INQUIRY_CREATED";
export const INQUIRY_ERROR = "INQUIRY_ERROR";
export const DELETE_INQUIRY = "DELETE_INQUIRY";
export const INQUIRY_UPDATED = "INQUIRY_UPDATED";
export const INQUIRY_LIST_UPDATED = "INQUIRY_LIST_UPDATED";
export const GET_INQUIRY_BY_ID = "GET_INQUIRY_BY_ID";
export const CHANGE_INQUIRY_STATUS = "CHANGE_INQUIRY_STATUS";
export const INQUIRY_SEARCH_PARAMATERS_UPDATE =
  "INQUIRY_SEARCH_PARAMATERS_UPDATE";

//Setting Constants
export const SETTING_ERROR = "SETTING_ERROR";
export const SETTING_UPDATED = "SETTING_UPDATED";
export const GET_SETTING = "GET_SETTING";

//Blog Constants
export const BLOG_CREATED = "BLOG_CREATED";
export const BLOG_ERROR = "BLOG_ERROR";
export const DELETE_BLOG = "DELETE_BLOG";
export const BLOG_UPDATED = "BLOG_UPDATED";
export const BLOG_LIST_UPDATED = "BLOG_LIST_UPDATED";
export const GET_BLOG_BY_ID = "GET_BLOG_BY_ID";
export const CHANGE_BLOG_STATUS = "CHANGE_BLOG_STATUS";
export const BLOG_SEARCH_PARAMATERS_UPDATE = "BLOG_SEARCH_PARAMATERS_UPDATE";

// Coupon Constants
export const COUPON_LOADING = "COUPON_LOADING";
export const COUPON_CREATED = "COUPON_CREATED";
export const COUPON_CREATE_ERROR = "COUPON_CREATE_ERROR";
export const COUPON_FAIL = "COUPON_FAIL";
export const COUPON_LIST_UPDATED = "COUPON_LIST_UPDATED";
export const COUPON_DELETED = "COUPON_DELETED";
export const COUPON_DELETE_ERROR = "COUPON_DELETE_ERROR";
export const GET_COUPON_BY_ID = "GET_COUPON_BY_ID";
export const COUPON_UPDATED = "COUPON_UPDATED";
export const COUPON_UPDATE_ERROR = "COUPON_UPDATE_ERROR";
export const COUPON_CHANGE_STATUS = "COUPON_CHANGE_STATUS";
export const COUPON_CHANGE_STATUS_ERROR = "COUPON_CHANGE_STATUS_ERROR";
export const COUPON_QUANTITY_INCRESED = "COUPON_QUANTITY_INCRESED";
export const CHANGE_COUPON_STATUS = "CHANGE_COUPON_STATUS";
export const COUPON_ADDED = "COUPON_ADDED";
export const COUPON_DEFAULT_LENGTH = "COUPON_DEFAULT_LENGTH";
export const COUPON_ERROR = "COUPON_ERROR";
export const COUPON_SEARCH_PARAMATERS_UPDATE =
  "COUPON_SEARCH_PARAMATERS_UPDATE";
export const DELETE_COUPON = "DELETE_COUPON";
